# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.0.1
_src_path: https://github.com/napari/napari-plugin-template
display_name: Mouse Tumour Annotation
email: bastien.chesauxdapia@epfl.ch
full_name: Bastien Chesaux Dapia
github_repository_url: https://github.com/bastienchesaux/napari-mouse-tumour-annotation
github_username_or_organization: bastienchesaux
include_reader_plugin: false
include_sample_data_plugin: true
include_widget_plugin: true
include_writer_plugin: false
install_dependabot: true
install_precommit: true
license: BSD-3
module_name: napari_mouse_tumour_annotation
plugin_name: napari-mouse-tumour-annotation
short_description: A plug-in to facilitate annotation of tumours in mouse CT-scans
    using a fine-tuned UNet model
